import { FOUNDER_EMAIL } from "@/lib/brand";

export const TEAM = [
  {
    id: "founder",
    displayName: "Krunal H Salvi",
    name: "Krunal H Salvi",
    role: "Founder & Lead Architect",
    email: FOUNDER_EMAIL,
    phone: "918-840-3501",
    specialty: "Vision, system architecture, client partnerships",
    stat: "Founder",
    featured: true,
    hidePersonalName: false,
    showEmail: true,
    icon: "◆",
  },
  {
    id: "natasha",
    displayName: "Natasha McGee",
    name: "Natasha McGee",
    role: "Manager & Sales Lead",
    email: FOUNDER_EMAIL,
    phone: undefined,
    specialty: "Client relationships, sales, project management",
    stat: "Your main point of contact",
    featured: false,
    hidePersonalName: false,
    showEmail: true,
    icon: "★",
  },
  {
    id: "alex",
    displayName: "Alex Rivera",
    name: "Alex Rivera",
    role: "Systems Engineer",
    email: FOUNDER_EMAIL,
    phone: undefined,
    specialty: "Voice AI, Twilio routing, infrastructure",
    stat: "Voice AI · n8n",
    featured: false,
    hidePersonalName: false,
    icon: "⚡",
  },
  {
    id: "elena",
    displayName: "Elena Morales",
    name: "Elena Morales",
    role: "Client Success Lead",
    email: FOUNDER_EMAIL,
    phone: undefined,
    specialty: "Onboarding, CRM setup, business workflows",
    stat: "12+ industries served",
    featured: false,
    hidePersonalName: false,
    icon: "✦",
  },
  {
    id: "marcus",
    displayName: "Marcus Chen",
    name: "Marcus Chen",
    role: "Automation Specialist",
    email: FOUNDER_EMAIL,
    phone: undefined,
    specialty: "n8n workflows, payments, lead response engines",
    stat: "15-sec response builds",
    featured: false,
    hidePersonalName: false,
    icon: "⟡",
  },
] as const;
